# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smiths_app', '0002_auto_20161215_0751'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customers',
            table='customers',
        ),
    ]
