# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smiths_app', '0003_auto_20161215_0754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('name', models.TextField()),
                ('barcode', models.IntegerField(primary_key=True, serialize=False)),
                ('available_units', models.TextField()),
                ('price', models.FloatField()),
                ('weigh_b', models.IntegerField()),
                ('provider', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('r_date', models.TextField(blank=True, null=True)),
                ('quantities', models.TextField(blank=True, null=True)),
                ('customer_id', models.IntegerField(blank=True, null=True)),
                ('barcodes', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'reservations',
            },
        ),
    ]
