# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'payment.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_payment_dialog(object):
    def setupUi(self, payment_dialog):
        payment_dialog.setObjectName("payment_dialog")
        payment_dialog.resize(625, 301)
        payment_dialog.setStyleSheet("#error_lb, #pay_with_points_lbl {\n"
"    color: red;\n"
"}\n"
"\n"
"#total_lbl, #total_lbl_2 {\n"
"    font-size: 16px;\n"
"}")
        self.cash_rb = QtWidgets.QRadioButton(payment_dialog)
        self.cash_rb.setGeometry(QtCore.QRect(39, 36, 103, 20))
        self.cash_rb.setChecked(True)
        self.cash_rb.setObjectName("cash_rb")
        self.buttonGroup = QtWidgets.QButtonGroup(payment_dialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.cash_rb)
        self.credit_rb = QtWidgets.QRadioButton(payment_dialog)
        self.credit_rb.setGeometry(QtCore.QRect(39, 56, 155, 20))
        self.credit_rb.setObjectName("credit_rb")
        self.buttonGroup.addButton(self.credit_rb)
        self.check_rb = QtWidgets.QRadioButton(payment_dialog)
        self.check_rb.setGeometry(QtCore.QRect(39, 76, 123, 20))
        self.check_rb.setObjectName("check_rb")
        self.buttonGroup.addButton(self.check_rb)
        self.print_btn = QtWidgets.QPushButton(payment_dialog)
        self.print_btn.setGeometry(QtCore.QRect(414, 33, 183, 35))
        self.print_btn.setObjectName("print_btn")
        self.total_lbl_2 = QtWidgets.QLabel(payment_dialog)
        self.total_lbl_2.setGeometry(QtCore.QRect(362, 73, 89, 27))
        self.total_lbl_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.total_lbl_2.setObjectName("total_lbl_2")
        self.total_lbl = QtWidgets.QLabel(payment_dialog)
        self.total_lbl.setGeometry(QtCore.QRect(456, 73, 137, 27))
        self.total_lbl.setStyleSheet("")
        self.total_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.total_lbl.setObjectName("total_lbl")
        self.customer_frame = QtWidgets.QFrame(payment_dialog)
        self.customer_frame.setGeometry(QtCore.QRect(15, 94, 397, 169))
        self.customer_frame.setStyleSheet("#customer_frame{\n"
"    border: none;\n"
"}")
        self.customer_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.customer_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.customer_frame.setObjectName("customer_frame")
        self.pay_with_points_lbl = QtWidgets.QLabel(self.customer_frame)
        self.pay_with_points_lbl.setGeometry(QtCore.QRect(89, 4, 299, 16))
        self.pay_with_points_lbl.setStyleSheet("")
        self.pay_with_points_lbl.setText("")
        self.pay_with_points_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.pay_with_points_lbl.setObjectName("pay_with_points_lbl")
        self.available_points_lbl_6 = QtWidgets.QLabel(self.customer_frame)
        self.available_points_lbl_6.setGeometry(QtCore.QRect(13, 78, 89, 16))
        self.available_points_lbl_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.available_points_lbl_6.setObjectName("available_points_lbl_6")
        self.customer_id_lbl = QtWidgets.QLabel(self.customer_frame)
        self.customer_id_lbl.setGeometry(QtCore.QRect(107, 78, 235, 16))
        self.customer_id_lbl.setText("")
        self.customer_id_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.customer_id_lbl.setObjectName("customer_id_lbl")
        self.available_points_lbl_2 = QtWidgets.QLabel(self.customer_frame)
        self.available_points_lbl_2.setGeometry(QtCore.QRect(13, 96, 89, 16))
        self.available_points_lbl_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.available_points_lbl_2.setObjectName("available_points_lbl_2")
        self.error_lbl = QtWidgets.QLabel(self.customer_frame)
        self.error_lbl.setGeometry(QtCore.QRect(5, 22, 273, 16))
        self.error_lbl.setText("")
        self.error_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.error_lbl.setObjectName("error_lbl")
        self.points_transaction_lbl = QtWidgets.QLabel(self.customer_frame)
        self.points_transaction_lbl.setGeometry(QtCore.QRect(107, 116, 265, 16))
        self.points_transaction_lbl.setStyleSheet("")
        self.points_transaction_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.points_transaction_lbl.setObjectName("points_transaction_lbl")
        self.available_points_lbl_3 = QtWidgets.QLabel(self.customer_frame)
        self.available_points_lbl_3.setGeometry(QtCore.QRect(13, 60, 89, 16))
        self.available_points_lbl_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.available_points_lbl_3.setObjectName("available_points_lbl_3")
        self.available_points_lbl = QtWidgets.QLabel(self.customer_frame)
        self.available_points_lbl.setGeometry(QtCore.QRect(107, 96, 137, 16))
        self.available_points_lbl.setText("")
        self.available_points_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.available_points_lbl.setObjectName("available_points_lbl")
        self.customer_name_lbl = QtWidgets.QLabel(self.customer_frame)
        self.customer_name_lbl.setGeometry(QtCore.QRect(107, 60, 235, 16))
        self.customer_name_lbl.setText("")
        self.customer_name_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.customer_name_lbl.setObjectName("customer_name_lbl")
        self.points_rb = QtWidgets.QRadioButton(self.customer_frame)
        self.points_rb.setEnabled(False)
        self.points_rb.setGeometry(QtCore.QRect(24, 2, 82, 20))
        self.points_rb.setObjectName("points_rb")
        self.buttonGroup.addButton(self.points_rb)
        self.customer_search_frame = QtWidgets.QFrame(payment_dialog)
        self.customer_search_frame.setGeometry(QtCore.QRect(414, 124, 207, 131))
        self.customer_search_frame.setStyleSheet("#customer_search_frame{\n"
"    border: none;\n"
"}")
        self.customer_search_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.customer_search_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.customer_search_frame.setObjectName("customer_search_frame")
        self.new_customer_cb = QtWidgets.QCheckBox(self.customer_search_frame)
        self.new_customer_cb.setGeometry(QtCore.QRect(74, 62, 125, 17))
        self.new_customer_cb.setCheckable(True)
        self.new_customer_cb.setObjectName("new_customer_cb")
        self.load_customer_info_btn = QtWidgets.QPushButton(self.customer_search_frame)
        self.load_customer_info_btn.setGeometry(QtCore.QRect(18, 88, 183, 35))
        self.load_customer_info_btn.setObjectName("load_customer_info_btn")
        self.customer_name_field = QtWidgets.QLineEdit(self.customer_search_frame)
        self.customer_name_field.setGeometry(QtCore.QRect(18, 12, 183, 20))
        self.customer_name_field.setClearButtonEnabled(True)
        self.customer_name_field.setObjectName("customer_name_field")
        self.customer_id_sbox = QtWidgets.QSpinBox(self.customer_search_frame)
        self.customer_id_sbox.setGeometry(QtCore.QRect(18, 38, 183, 20))
        self.customer_id_sbox.setWrapping(True)
        self.customer_id_sbox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.customer_id_sbox.setProperty("showGroupSeparator", False)
        self.customer_id_sbox.setSuffix("")
        self.customer_id_sbox.setMinimum(0)
        self.customer_id_sbox.setMaximum(999999)
        self.customer_id_sbox.setProperty("value", 0)
        self.customer_id_sbox.setObjectName("customer_id_sbox")
        self.id_lbl = QtWidgets.QLabel(self.customer_search_frame)
        self.id_lbl.setGeometry(QtCore.QRect(-8, 40, 21, 16))
        self.id_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.id_lbl.setObjectName("id_lbl")

        self.retranslateUi(payment_dialog)
        QtCore.QMetaObject.connectSlotsByName(payment_dialog)

    def retranslateUi(self, payment_dialog):
        _translate = QtCore.QCoreApplication.translate
        payment_dialog.setWindowTitle(_translate("payment_dialog", "Dialog"))
        self.cash_rb.setText(_translate("payment_dialog", "Cash"))
        self.credit_rb.setText(_translate("payment_dialog", "Credit Card"))
        self.check_rb.setText(_translate("payment_dialog", "Check"))
        self.print_btn.setText(_translate("payment_dialog", "Print Receipt"))
        self.total_lbl_2.setText(_translate("payment_dialog", "Total"))
        self.total_lbl.setText(_translate("payment_dialog", "$"))
        self.available_points_lbl_6.setText(_translate("payment_dialog", "Customer ID"))
        self.available_points_lbl_2.setText(_translate("payment_dialog", "Available Points"))
        self.points_transaction_lbl.setText(_translate("payment_dialog", "Transaction will add 100 points"))
        self.available_points_lbl_3.setText(_translate("payment_dialog", "Customer Name"))
        self.points_rb.setText(_translate("payment_dialog", "Points"))
        self.new_customer_cb.setText(_translate("payment_dialog", "Create New Customer"))
        self.load_customer_info_btn.setText(_translate("payment_dialog", "Load Customer Info"))
        self.customer_name_field.setPlaceholderText(_translate("payment_dialog", "Customer Name"))
        self.id_lbl.setText(_translate("payment_dialog", "ID"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    payment_dialog = QtWidgets.QDialog()
    ui = Ui_payment_dialog()
    ui.setupUi(payment_dialog)
    payment_dialog.show()
    sys.exit(app.exec_())

