# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'smith.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(1114, 771)
        main_window.setStyleSheet("#employee_name_lbl, #employee_id_lbl, #bc_name_lbl {\n"
"    font-size: 22px;\n"
"}\n"
"#error_lbl {\n"
"    color: red;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(12, 39, 1091, 686))
        self.tabWidget.setObjectName("tabWidget")
        self.manage_employees_tab = QtWidgets.QWidget()
        self.manage_employees_tab.setObjectName("manage_employees_tab")
        self.me_employee_listview = QtWidgets.QListView(self.manage_employees_tab)
        self.me_employee_listview.setGeometry(QtCore.QRect(16, 20, 256, 629))
        self.me_employee_listview.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.me_employee_listview.setProperty("showDropIndicator", False)
        self.me_employee_listview.setObjectName("me_employee_listview")
        self.me_employee_gbox = QtWidgets.QGroupBox(self.manage_employees_tab)
        self.me_employee_gbox.setEnabled(False)
        self.me_employee_gbox.setGeometry(QtCore.QRect(288, 15, 509, 229))
        self.me_employee_gbox.setObjectName("me_employee_gbox")
        self.me_delete_employee_btn = QtWidgets.QPushButton(self.me_employee_gbox)
        self.me_delete_employee_btn.setGeometry(QtCore.QRect(298, 69, 183, 35))
        self.me_delete_employee_btn.setObjectName("me_delete_employee_btn")
        self.label_4 = QtWidgets.QLabel(self.me_employee_gbox)
        self.label_4.setGeometry(QtCore.QRect(14, 29, 89, 13))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.me_update_employee_btn = QtWidgets.QPushButton(self.me_employee_gbox)
        self.me_update_employee_btn.setGeometry(QtCore.QRect(72, 168, 183, 35))
        self.me_update_employee_btn.setObjectName("me_update_employee_btn")
        self.label_5 = QtWidgets.QLabel(self.me_employee_gbox)
        self.label_5.setGeometry(QtCore.QRect(14, 61, 89, 13))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.me_employee_gbox)
        self.label_6.setGeometry(QtCore.QRect(14, 95, 89, 13))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.me_password_field = QtWidgets.QLineEdit(self.me_employee_gbox)
        self.me_password_field.setGeometry(QtCore.QRect(109, 91, 161, 20))
        self.me_password_field.setEchoMode(QtWidgets.QLineEdit.Password)
        self.me_password_field.setObjectName("me_password_field")
        self.me_name_field = QtWidgets.QLineEdit(self.me_employee_gbox)
        self.me_name_field.setGeometry(QtCore.QRect(109, 57, 161, 20))
        self.me_name_field.setObjectName("me_name_field")
        self.me_id_lbl = QtWidgets.QLabel(self.me_employee_gbox)
        self.me_id_lbl.setGeometry(QtCore.QRect(110, 29, 89, 13))
        self.me_id_lbl.setText("")
        self.me_id_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.me_id_lbl.setObjectName("me_id_lbl")
        self.me_role_cbox = QtWidgets.QComboBox(self.me_employee_gbox)
        self.me_role_cbox.setGeometry(QtCore.QRect(108, 126, 161, 22))
        self.me_role_cbox.setObjectName("me_role_cbox")
        self.me_role_cbox.addItem("")
        self.me_role_cbox.addItem("")
        self.me_create_new_employee_btn = QtWidgets.QPushButton(self.manage_employees_tab)
        self.me_create_new_employee_btn.setGeometry(QtCore.QRect(585, 40, 183, 35))
        self.me_create_new_employee_btn.setObjectName("me_create_new_employee_btn")
        self.tabWidget.addTab(self.manage_employees_tab, "")
        self.manage_products_tab = QtWidgets.QWidget()
        self.manage_products_tab.setObjectName("manage_products_tab")
        self.label_33 = QtWidgets.QLabel(self.manage_products_tab)
        self.label_33.setGeometry(QtCore.QRect(16, 42, 89, 13))
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName("label_33")
        self.mp_barcode_search_field = QtWidgets.QLineEdit(self.manage_products_tab)
        self.mp_barcode_search_field.setGeometry(QtCore.QRect(112, 38, 161, 20))
        self.mp_barcode_search_field.setObjectName("mp_barcode_search_field")
        self.mp_search_btn = QtWidgets.QPushButton(self.manage_products_tab)
        self.mp_search_btn.setGeometry(QtCore.QRect(68, 75, 183, 35))
        self.mp_search_btn.setObjectName("mp_search_btn")
        self.mp_product_gbox = QtWidgets.QGroupBox(self.manage_products_tab)
        self.mp_product_gbox.setEnabled(False)
        self.mp_product_gbox.setGeometry(QtCore.QRect(342, 18, 535, 395))
        self.mp_product_gbox.setObjectName("mp_product_gbox")
        self.mp_delete_btn = QtWidgets.QPushButton(self.mp_product_gbox)
        self.mp_delete_btn.setGeometry(QtCore.QRect(300, 70, 183, 35))
        self.mp_delete_btn.setObjectName("mp_delete_btn")
        self.mp_name_field = QtWidgets.QLineEdit(self.mp_product_gbox)
        self.mp_name_field.setGeometry(QtCore.QRect(107, 24, 161, 20))
        self.mp_name_field.setObjectName("mp_name_field")
        self.mp_update_btn = QtWidgets.QPushButton(self.mp_product_gbox)
        self.mp_update_btn.setGeometry(QtCore.QRect(80, 340, 183, 35))
        self.mp_update_btn.setObjectName("mp_update_btn")
        self.label_9 = QtWidgets.QLabel(self.mp_product_gbox)
        self.label_9.setGeometry(QtCore.QRect(11, 94, 89, 13))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.label_15 = QtWidgets.QLabel(self.mp_product_gbox)
        self.label_15.setGeometry(QtCore.QRect(11, 162, 89, 13))
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.label_13 = QtWidgets.QLabel(self.mp_product_gbox)
        self.label_13.setGeometry(QtCore.QRect(11, 256, 89, 13))
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.label_12 = QtWidgets.QLabel(self.mp_product_gbox)
        self.label_12.setGeometry(QtCore.QRect(11, 130, 89, 13))
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.label_11 = QtWidgets.QLabel(self.mp_product_gbox)
        self.label_11.setGeometry(QtCore.QRect(11, 28, 89, 13))
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.label_10 = QtWidgets.QLabel(self.mp_product_gbox)
        self.label_10.setGeometry(QtCore.QRect(11, 60, 89, 13))
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.mp_weight_rb = QtWidgets.QRadioButton(self.mp_product_gbox)
        self.mp_weight_rb.setGeometry(QtCore.QRect(108, 216, 82, 17))
        self.mp_weight_rb.setObjectName("mp_weight_rb")
        self.mp_quantity_rb = QtWidgets.QRadioButton(self.mp_product_gbox)
        self.mp_quantity_rb.setGeometry(QtCore.QRect(108, 196, 82, 17))
        self.mp_quantity_rb.setObjectName("mp_quantity_rb")
        self.label_19 = QtWidgets.QLabel(self.mp_product_gbox)
        self.label_19.setGeometry(QtCore.QRect(10, 206, 89, 13))
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.mp_provider_sbox = QtWidgets.QSpinBox(self.mp_product_gbox)
        self.mp_provider_sbox.setGeometry(QtCore.QRect(107, 252, 78, 22))
        self.mp_provider_sbox.setWrapping(True)
        self.mp_provider_sbox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.mp_provider_sbox.setProperty("showGroupSeparator", False)
        self.mp_provider_sbox.setSuffix("")
        self.mp_provider_sbox.setMinimum(0)
        self.mp_provider_sbox.setMaximum(999999)
        self.mp_provider_sbox.setProperty("value", 0)
        self.mp_provider_sbox.setObjectName("mp_provider_sbox")
        self.mp_customer_price_sbox = QtWidgets.QDoubleSpinBox(self.mp_product_gbox)
        self.mp_customer_price_sbox.setGeometry(QtCore.QRect(107, 158, 78, 22))
        self.mp_customer_price_sbox.setWrapping(True)
        self.mp_customer_price_sbox.setProperty("showGroupSeparator", False)
        self.mp_customer_price_sbox.setMaximum(99999.99)
        self.mp_customer_price_sbox.setProperty("value", 0.0)
        self.mp_customer_price_sbox.setObjectName("mp_customer_price_sbox")
        self.mp_price_sbox = QtWidgets.QDoubleSpinBox(self.mp_product_gbox)
        self.mp_price_sbox.setGeometry(QtCore.QRect(107, 126, 78, 22))
        self.mp_price_sbox.setWrapping(True)
        self.mp_price_sbox.setProperty("showGroupSeparator", False)
        self.mp_price_sbox.setMaximum(99999.99)
        self.mp_price_sbox.setProperty("value", 0.0)
        self.mp_price_sbox.setObjectName("mp_price_sbox")
        self.mp_available_units_sbox = QtWidgets.QSpinBox(self.mp_product_gbox)
        self.mp_available_units_sbox.setGeometry(QtCore.QRect(107, 90, 57, 22))
        self.mp_available_units_sbox.setWrapping(True)
        self.mp_available_units_sbox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.mp_available_units_sbox.setProperty("showGroupSeparator", False)
        self.mp_available_units_sbox.setSuffix("")
        self.mp_available_units_sbox.setMinimum(0)
        self.mp_available_units_sbox.setMaximum(999999)
        self.mp_available_units_sbox.setProperty("value", 0)
        self.mp_available_units_sbox.setObjectName("mp_available_units_sbox")
        self.mp_barcode_sbox = QtWidgets.QSpinBox(self.mp_product_gbox)
        self.mp_barcode_sbox.setGeometry(QtCore.QRect(107, 56, 78, 22))
        self.mp_barcode_sbox.setWrapping(True)
        self.mp_barcode_sbox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.mp_barcode_sbox.setProperty("showGroupSeparator", False)
        self.mp_barcode_sbox.setSuffix("")
        self.mp_barcode_sbox.setMinimum(0)
        self.mp_barcode_sbox.setMaximum(999999)
        self.mp_barcode_sbox.setProperty("value", 0)
        self.mp_barcode_sbox.setObjectName("mp_barcode_sbox")
        self.mp_available_units_2_sbox = QtWidgets.QDoubleSpinBox(self.mp_product_gbox)
        self.mp_available_units_2_sbox.setGeometry(QtCore.QRect(170, 90, 65, 22))
        self.mp_available_units_2_sbox.setWrapping(True)
        self.mp_available_units_2_sbox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mp_available_units_2_sbox.setProperty("showGroupSeparator", False)
        self.mp_available_units_2_sbox.setMaximum(0.99)
        self.mp_available_units_2_sbox.setSingleStep(0.01)
        self.mp_available_units_2_sbox.setProperty("value", 0.0)
        self.mp_available_units_2_sbox.setObjectName("mp_available_units_2_sbox")
        self.white_space = QtWidgets.QPushButton(self.mp_product_gbox)
        self.white_space.setGeometry(QtCore.QRect(172, 92, 10, 17))
        self.white_space.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: none;\n"
"}")
        self.white_space.setText("")
        self.white_space.setObjectName("white_space")
        self.mp_add_btn = QtWidgets.QPushButton(self.manage_products_tab)
        self.mp_add_btn.setGeometry(QtCore.QRect(642, 42, 183, 35))
        self.mp_add_btn.setObjectName("mp_add_btn")
        self.mp_import_btn = QtWidgets.QPushButton(self.manage_products_tab)
        self.mp_import_btn.setGeometry(QtCore.QRect(886, 610, 183, 35))
        self.mp_import_btn.setObjectName("mp_import_btn")
        self.label_33.raise_()
        self.mp_barcode_search_field.raise_()
        self.mp_search_btn.raise_()
        self.mp_product_gbox.raise_()
        self.mp_add_btn.raise_()
        self.mp_import_btn.raise_()
        self.mp_customer_price_sbox.raise_()
        self.mp_price_sbox.raise_()
        self.tabWidget.addTab(self.manage_products_tab, "")
        self.manage_customers_tab = QtWidgets.QWidget()
        self.manage_customers_tab.setObjectName("manage_customers_tab")
        self.groupBox_5 = QtWidgets.QGroupBox(self.manage_customers_tab)
        self.groupBox_5.setGeometry(QtCore.QRect(390, 266, 535, 155))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_24 = QtWidgets.QLabel(self.groupBox_5)
        self.label_24.setGeometry(QtCore.QRect(100, 26, 89, 16))
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.label_26 = QtWidgets.QLabel(self.groupBox_5)
        self.label_26.setGeometry(QtCore.QRect(282, 26, 237, 16))
        self.label_26.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.groupBox_5)
        self.label_27.setGeometry(QtCore.QRect(282, 58, 297, 16))
        self.label_27.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.label_31 = QtWidgets.QLabel(self.groupBox_5)
        self.label_31.setGeometry(QtCore.QRect(20, 58, 167, 16))
        self.label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.earn_sbox = QtWidgets.QSpinBox(self.groupBox_5)
        self.earn_sbox.setGeometry(QtCore.QRect(196, 24, 79, 22))
        self.earn_sbox.setWrapping(True)
        self.earn_sbox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.earn_sbox.setMinimum(0)
        self.earn_sbox.setMaximum(9999)
        self.earn_sbox.setProperty("value", 1)
        self.earn_sbox.setObjectName("earn_sbox")
        self.spend_sbox = QtWidgets.QSpinBox(self.groupBox_5)
        self.spend_sbox.setGeometry(QtCore.QRect(196, 56, 79, 22))
        self.spend_sbox.setWrapping(True)
        self.spend_sbox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spend_sbox.setMinimum(1)
        self.spend_sbox.setMaximum(9999)
        self.spend_sbox.setProperty("value", 100)
        self.spend_sbox.setObjectName("spend_sbox")
        self.mc_update_rules_btn = QtWidgets.QPushButton(self.groupBox_5)
        self.mc_update_rules_btn.setGeometry(QtCore.QRect(170, 98, 183, 35))
        self.mc_update_rules_btn.setObjectName("mc_update_rules_btn")
        self.label_38 = QtWidgets.QLabel(self.manage_customers_tab)
        self.label_38.setGeometry(QtCore.QRect(6, 46, 145, 13))
        self.label_38.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_38.setObjectName("label_38")
        self.mc_search_btn = QtWidgets.QPushButton(self.manage_customers_tab)
        self.mc_search_btn.setGeometry(QtCore.QRect(114, 79, 183, 35))
        self.mc_search_btn.setObjectName("mc_search_btn")
        self.mc_name_id_search_field = QtWidgets.QLineEdit(self.manage_customers_tab)
        self.mc_name_id_search_field.setGeometry(QtCore.QRect(158, 42, 161, 20))
        self.mc_name_id_search_field.setObjectName("mc_name_id_search_field")
        self.mc_customer_gbox = QtWidgets.QGroupBox(self.manage_customers_tab)
        self.mc_customer_gbox.setEnabled(False)
        self.mc_customer_gbox.setGeometry(QtCore.QRect(390, 22, 535, 219))
        self.mc_customer_gbox.setObjectName("mc_customer_gbox")
        self.mc_name_field = QtWidgets.QLineEdit(self.mc_customer_gbox)
        self.mc_name_field.setGeometry(QtCore.QRect(107, 24, 161, 20))
        self.mc_name_field.setObjectName("mc_name_field")
        self.mc_update_btn = QtWidgets.QPushButton(self.mc_customer_gbox)
        self.mc_update_btn.setGeometry(QtCore.QRect(184, 148, 183, 35))
        self.mc_update_btn.setObjectName("mc_update_btn")
        self.label_39 = QtWidgets.QLabel(self.mc_customer_gbox)
        self.label_39.setGeometry(QtCore.QRect(11, 94, 89, 13))
        self.label_39.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_39.setObjectName("label_39")
        self.label_44 = QtWidgets.QLabel(self.mc_customer_gbox)
        self.label_44.setGeometry(QtCore.QRect(11, 28, 89, 13))
        self.label_44.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.mc_customer_gbox)
        self.label_45.setGeometry(QtCore.QRect(11, 60, 89, 13))
        self.label_45.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_45.setObjectName("label_45")
        self.mc_id_lbl = QtWidgets.QLabel(self.mc_customer_gbox)
        self.mc_id_lbl.setGeometry(QtCore.QRect(107, 60, 89, 13))
        self.mc_id_lbl.setText("")
        self.mc_id_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.mc_id_lbl.setObjectName("mc_id_lbl")
        self.mc_point_balance_sbox = QtWidgets.QSpinBox(self.mc_customer_gbox)
        self.mc_point_balance_sbox.setGeometry(QtCore.QRect(107, 89, 125, 22))
        self.mc_point_balance_sbox.setWrapping(True)
        self.mc_point_balance_sbox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.mc_point_balance_sbox.setMinimum(0)
        self.mc_point_balance_sbox.setMaximum(9999)
        self.mc_point_balance_sbox.setProperty("value", 0)
        self.mc_point_balance_sbox.setObjectName("mc_point_balance_sbox")
        self.mc_activity_cb = QtWidgets.QCheckBox(self.mc_customer_gbox)
        self.mc_activity_cb.setGeometry(QtCore.QRect(346, 82, 133, 17))
        self.mc_activity_cb.setChecked(True)
        self.mc_activity_cb.setObjectName("mc_activity_cb")
        self.mc_add_btn = QtWidgets.QPushButton(self.manage_customers_tab)
        self.mc_add_btn.setGeometry(QtCore.QRect(704, 50, 183, 35))
        self.mc_add_btn.setObjectName("mc_add_btn")
        self.tabWidget.addTab(self.manage_customers_tab, "")
        self.manage_orders_tab = QtWidgets.QWidget()
        self.manage_orders_tab.setObjectName("manage_orders_tab")
        self.mo_date_lbl = QtWidgets.QLabel(self.manage_orders_tab)
        self.mo_date_lbl.setGeometry(QtCore.QRect(24, 266, 239, 16))
        self.mo_date_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.mo_date_lbl.setObjectName("mo_date_lbl")
        self.groupBox = QtWidgets.QGroupBox(self.manage_orders_tab)
        self.groupBox.setGeometry(QtCore.QRect(24, 16, 241, 115))
        self.groupBox.setObjectName("groupBox")
        self.label_34 = QtWidgets.QLabel(self.groupBox)
        self.label_34.setGeometry(QtCore.QRect(4, 28, 59, 13))
        self.label_34.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_34.setObjectName("label_34")
        self.mo_id_search_field = QtWidgets.QLineEdit(self.groupBox)
        self.mo_id_search_field.setGeometry(QtCore.QRect(70, 24, 161, 20))
        self.mo_id_search_field.setObjectName("mo_id_search_field")
        self.mo_search_btn = QtWidgets.QPushButton(self.groupBox)
        self.mo_search_btn.setGeometry(QtCore.QRect(26, 61, 183, 35))
        self.mo_search_btn.setObjectName("mo_search_btn")
        self.groupBox_2 = QtWidgets.QGroupBox(self.manage_orders_tab)
        self.groupBox_2.setGeometry(QtCore.QRect(22, 188, 241, 63))
        self.groupBox_2.setObjectName("groupBox_2")
        self.mo_date_edit = QtWidgets.QDateEdit(self.groupBox_2)
        self.mo_date_edit.setGeometry(QtCore.QRect(12, 24, 110, 22))
        self.mo_date_edit.setCurrentSection(QtWidgets.QDateTimeEdit.MonthSection)
        self.mo_date_edit.setCalendarPopup(True)
        self.mo_date_edit.setObjectName("mo_date_edit")
        self.mo_receipt_frame = QtWidgets.QFrame(self.manage_orders_tab)
        self.mo_receipt_frame.setEnabled(False)
        self.mo_receipt_frame.setGeometry(QtCore.QRect(594, 10, 319, 641))
        self.mo_receipt_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mo_receipt_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mo_receipt_frame.setObjectName("mo_receipt_frame")
        self.mo_total_lbl = QtWidgets.QLabel(self.mo_receipt_frame)
        self.mo_total_lbl.setGeometry(QtCore.QRect(212, 620, 86, 16))
        self.mo_total_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mo_total_lbl.setObjectName("mo_total_lbl")
        self.mo_r_subtotal_lbl = QtWidgets.QLabel(self.mo_receipt_frame)
        self.mo_r_subtotal_lbl.setGeometry(QtCore.QRect(212, 580, 86, 16))
        self.mo_r_subtotal_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mo_r_subtotal_lbl.setObjectName("mo_r_subtotal_lbl")
        self.label_20 = QtWidgets.QLabel(self.mo_receipt_frame)
        self.label_20.setGeometry(QtCore.QRect(148, 580, 56, 16))
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.label_22 = QtWidgets.QLabel(self.mo_receipt_frame)
        self.label_22.setGeometry(QtCore.QRect(148, 620, 56, 16))
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.mo_receipt_listview = QtWidgets.QListView(self.mo_receipt_frame)
        self.mo_receipt_listview.setGeometry(QtCore.QRect(63, 5, 241, 571))
        self.mo_receipt_listview.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.mo_receipt_listview.setProperty("showDropIndicator", False)
        self.mo_receipt_listview.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.mo_receipt_listview.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.mo_receipt_listview.setObjectName("mo_receipt_listview")
        self.mo_tax_lbl = QtWidgets.QLabel(self.mo_receipt_frame)
        self.mo_tax_lbl.setGeometry(QtCore.QRect(212, 600, 86, 16))
        self.mo_tax_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mo_tax_lbl.setObjectName("mo_tax_lbl")
        self.label_23 = QtWidgets.QLabel(self.mo_receipt_frame)
        self.label_23.setGeometry(QtCore.QRect(148, 600, 56, 16))
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.mo_btn_frame = QtWidgets.QFrame(self.manage_orders_tab)
        self.mo_btn_frame.setEnabled(False)
        self.mo_btn_frame.setGeometry(QtCore.QRect(364, 10, 221, 61))
        self.mo_btn_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mo_btn_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mo_btn_frame.setObjectName("mo_btn_frame")
        self.mo_return_btn = QtWidgets.QPushButton(self.mo_btn_frame)
        self.mo_return_btn.setGeometry(QtCore.QRect(20, 13, 183, 35))
        self.mo_return_btn.setObjectName("mo_return_btn")
        self.mo_receipt_date_listview = QtWidgets.QListView(self.manage_orders_tab)
        self.mo_receipt_date_listview.setGeometry(QtCore.QRect(22, 284, 241, 351))
        self.mo_receipt_date_listview.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.mo_receipt_date_listview.setProperty("showDropIndicator", False)
        self.mo_receipt_date_listview.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.mo_receipt_date_listview.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.mo_receipt_date_listview.setObjectName("mo_receipt_date_listview")
        self.mo_date_lbl_3 = QtWidgets.QLabel(self.manage_orders_tab)
        self.mo_date_lbl_3.setGeometry(QtCore.QRect(110, 154, 59, 13))
        self.mo_date_lbl_3.setAlignment(QtCore.Qt.AlignCenter)
        self.mo_date_lbl_3.setObjectName("mo_date_lbl_3")
        self.mo_r_date_lbl_33 = QtWidgets.QLabel(self.manage_orders_tab)
        self.mo_r_date_lbl_33.setGeometry(QtCore.QRect(316, 100, 99, 16))
        self.mo_r_date_lbl_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mo_r_date_lbl_33.setObjectName("mo_r_date_lbl_33")
        self.mo_r_date_lbl_2 = QtWidgets.QLabel(self.manage_orders_tab)
        self.mo_r_date_lbl_2.setGeometry(QtCore.QRect(316, 120, 99, 16))
        self.mo_r_date_lbl_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mo_r_date_lbl_2.setObjectName("mo_r_date_lbl_2")
        self.mo_r_date_lbl_3 = QtWidgets.QLabel(self.manage_orders_tab)
        self.mo_r_date_lbl_3.setGeometry(QtCore.QRect(316, 140, 99, 16))
        self.mo_r_date_lbl_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mo_r_date_lbl_3.setObjectName("mo_r_date_lbl_3")
        self.mo_r_date_lbl_4 = QtWidgets.QLabel(self.manage_orders_tab)
        self.mo_r_date_lbl_4.setGeometry(QtCore.QRect(316, 80, 99, 16))
        self.mo_r_date_lbl_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mo_r_date_lbl_4.setObjectName("mo_r_date_lbl_4")
        self.mo_r_method_lbl = QtWidgets.QLabel(self.manage_orders_tab)
        self.mo_r_method_lbl.setGeometry(QtCore.QRect(426, 140, 199, 16))
        self.mo_r_method_lbl.setText("")
        self.mo_r_method_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.mo_r_method_lbl.setObjectName("mo_r_method_lbl")
        self.mo_r_date_lbl = QtWidgets.QLabel(self.manage_orders_tab)
        self.mo_r_date_lbl.setGeometry(QtCore.QRect(426, 100, 199, 16))
        self.mo_r_date_lbl.setText("")
        self.mo_r_date_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.mo_r_date_lbl.setObjectName("mo_r_date_lbl")
        self.mo_r_cashier_lbl = QtWidgets.QLabel(self.manage_orders_tab)
        self.mo_r_cashier_lbl.setGeometry(QtCore.QRect(426, 120, 199, 16))
        self.mo_r_cashier_lbl.setText("")
        self.mo_r_cashier_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.mo_r_cashier_lbl.setObjectName("mo_r_cashier_lbl")
        self.mo_r_id_lbl = QtWidgets.QLabel(self.manage_orders_tab)
        self.mo_r_id_lbl.setGeometry(QtCore.QRect(426, 80, 199, 16))
        self.mo_r_id_lbl.setText("")
        self.mo_r_id_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.mo_r_id_lbl.setObjectName("mo_r_id_lbl")
        self.tabWidget.addTab(self.manage_orders_tab, "")
        self.reports_tab = QtWidgets.QWidget()
        self.reports_tab.setObjectName("reports_tab")
        self.r_date_edit_start = QtWidgets.QDateEdit(self.reports_tab)
        self.r_date_edit_start.setGeometry(QtCore.QRect(790, 24, 110, 22))
        self.r_date_edit_start.setCurrentSection(QtWidgets.QDateTimeEdit.MonthSection)
        self.r_date_edit_start.setCalendarPopup(True)
        self.r_date_edit_start.setObjectName("r_date_edit_start")
        self.r_date_edit_end = QtWidgets.QDateEdit(self.reports_tab)
        self.r_date_edit_end.setGeometry(QtCore.QRect(942, 24, 110, 22))
        self.r_date_edit_end.setTime(QtCore.QTime(0, 0, 0))
        self.r_date_edit_end.setCurrentSection(QtWidgets.QDateTimeEdit.MonthSection)
        self.r_date_edit_end.setCalendarPopup(True)
        self.r_date_edit_end.setObjectName("r_date_edit_end")
        self.r_beg_lbl = QtWidgets.QLabel(self.reports_tab)
        self.r_beg_lbl.setGeometry(QtCore.QRect(790, 6, 113, 16))
        self.r_beg_lbl.setObjectName("r_beg_lbl")
        self.r_end_lbl = QtWidgets.QLabel(self.reports_tab)
        self.r_end_lbl.setGeometry(QtCore.QRect(942, 6, 113, 16))
        self.r_end_lbl.setObjectName("r_end_lbl")
        self.report_table = QtWidgets.QTableView(self.reports_tab)
        self.report_table.setGeometry(QtCore.QRect(30, 62, 1023, 497))
        self.report_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.report_table.setTabKeyNavigation(False)
        self.report_table.setProperty("showDropIndicator", False)
        self.report_table.setAlternatingRowColors(True)
        self.report_table.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.report_table.setShowGrid(False)
        self.report_table.setSortingEnabled(True)
        self.report_table.setObjectName("report_table")
        self.r_print_btn = QtWidgets.QPushButton(self.reports_tab)
        self.r_print_btn.setGeometry(QtCore.QRect(980, 626, 75, 23))
        self.r_print_btn.setObjectName("r_print_btn")
        self.r_total_orders_lbl = QtWidgets.QLabel(self.reports_tab)
        self.r_total_orders_lbl.setGeometry(QtCore.QRect(956, 572, 95, 13))
        self.r_total_orders_lbl.setText("")
        self.r_total_orders_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.r_total_orders_lbl.setObjectName("r_total_orders_lbl")
        self.label_3 = QtWidgets.QLabel(self.reports_tab)
        self.label_3.setGeometry(QtCore.QRect(874, 572, 87, 13))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.r_total_revenue_lbl = QtWidgets.QLabel(self.reports_tab)
        self.r_total_revenue_lbl.setGeometry(QtCore.QRect(956, 590, 95, 13))
        self.r_total_revenue_lbl.setText("")
        self.r_total_revenue_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.r_total_revenue_lbl.setObjectName("r_total_revenue_lbl")
        self.label_25 = QtWidgets.QLabel(self.reports_tab)
        self.label_25.setGeometry(QtCore.QRect(874, 590, 87, 13))
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.groupBox_3 = QtWidgets.QGroupBox(self.reports_tab)
        self.groupBox_3.setGeometry(QtCore.QRect(746, 566, 120, 91))
        self.groupBox_3.setObjectName("groupBox_3")
        self.r_revenue_rb = QtWidgets.QRadioButton(self.groupBox_3)
        self.r_revenue_rb.setGeometry(QtCore.QRect(14, 70, 91, 17))
        self.r_revenue_rb.setObjectName("r_revenue_rb")
        self.r_total_rb = QtWidgets.QRadioButton(self.groupBox_3)
        self.r_total_rb.setGeometry(QtCore.QRect(14, 52, 82, 17))
        self.r_total_rb.setObjectName("r_total_rb")
        self.r_unordered_rb = QtWidgets.QRadioButton(self.groupBox_3)
        self.r_unordered_rb.setGeometry(QtCore.QRect(14, 16, 82, 17))
        self.r_unordered_rb.setChecked(True)
        self.r_unordered_rb.setObjectName("r_unordered_rb")
        self.r_alpha_rb = QtWidgets.QRadioButton(self.groupBox_3)
        self.r_alpha_rb.setGeometry(QtCore.QRect(14, 34, 91, 17))
        self.r_alpha_rb.setObjectName("r_alpha_rb")
        self.groupBox_4 = QtWidgets.QGroupBox(self.reports_tab)
        self.groupBox_4.setGeometry(QtCore.QRect(616, 566, 120, 59))
        self.groupBox_4.setObjectName("groupBox_4")
        self.r_asc_rb = QtWidgets.QRadioButton(self.groupBox_4)
        self.r_asc_rb.setGeometry(QtCore.QRect(14, 16, 82, 17))
        self.r_asc_rb.setChecked(True)
        self.r_asc_rb.setObjectName("r_asc_rb")
        self.r_desc_rb = QtWidgets.QRadioButton(self.groupBox_4)
        self.r_desc_rb.setGeometry(QtCore.QRect(14, 34, 91, 17))
        self.r_desc_rb.setObjectName("r_desc_rb")
        self.tabWidget.addTab(self.reports_tab, "")
        self.begin_checkout_tab = QtWidgets.QWidget()
        self.begin_checkout_tab.setObjectName("begin_checkout_tab")
        self.bc_begin_checkout_btn = QtWidgets.QPushButton(self.begin_checkout_tab)
        self.bc_begin_checkout_btn.setGeometry(QtCore.QRect(465, 200, 183, 35))
        self.bc_begin_checkout_btn.setObjectName("bc_begin_checkout_btn")
        self.bc_checkout_frame = QtWidgets.QFrame(self.begin_checkout_tab)
        self.bc_checkout_frame.setGeometry(QtCore.QRect(10, 10, 1066, 646))
        self.bc_checkout_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bc_checkout_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bc_checkout_frame.setObjectName("bc_checkout_frame")
        self.bc_receipt_frame = QtWidgets.QFrame(self.bc_checkout_frame)
        self.bc_receipt_frame.setEnabled(False)
        self.bc_receipt_frame.setGeometry(QtCore.QRect(584, 0, 319, 641))
        self.bc_receipt_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bc_receipt_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bc_receipt_frame.setObjectName("bc_receipt_frame")
        self.bc_total_lbl = QtWidgets.QLabel(self.bc_receipt_frame)
        self.bc_total_lbl.setGeometry(QtCore.QRect(212, 620, 86, 16))
        self.bc_total_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bc_total_lbl.setObjectName("bc_total_lbl")
        self.bc_r_subtotal_lbl = QtWidgets.QLabel(self.bc_receipt_frame)
        self.bc_r_subtotal_lbl.setGeometry(QtCore.QRect(212, 580, 86, 16))
        self.bc_r_subtotal_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bc_r_subtotal_lbl.setObjectName("bc_r_subtotal_lbl")
        self.label_18 = QtWidgets.QLabel(self.bc_receipt_frame)
        self.label_18.setGeometry(QtCore.QRect(148, 580, 56, 16))
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.label_17 = QtWidgets.QLabel(self.bc_receipt_frame)
        self.label_17.setGeometry(QtCore.QRect(148, 620, 56, 16))
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.bc_receipt_listview = QtWidgets.QListView(self.bc_receipt_frame)
        self.bc_receipt_listview.setGeometry(QtCore.QRect(63, 5, 241, 571))
        self.bc_receipt_listview.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.bc_receipt_listview.setProperty("showDropIndicator", False)
        self.bc_receipt_listview.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.bc_receipt_listview.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.bc_receipt_listview.setObjectName("bc_receipt_listview")
        self.bc_tax_lbl = QtWidgets.QLabel(self.bc_receipt_frame)
        self.bc_tax_lbl.setGeometry(QtCore.QRect(212, 600, 86, 16))
        self.bc_tax_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bc_tax_lbl.setObjectName("bc_tax_lbl")
        self.label_16 = QtWidgets.QLabel(self.bc_receipt_frame)
        self.label_16.setGeometry(QtCore.QRect(148, 600, 56, 16))
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.bc_cancel_btn = QtWidgets.QPushButton(self.bc_checkout_frame)
        self.bc_cancel_btn.setEnabled(False)
        self.bc_cancel_btn.setGeometry(QtCore.QRect(12, 598, 183, 35))
        self.bc_cancel_btn.setObjectName("bc_cancel_btn")
        self.bc_gbox = QtWidgets.QGroupBox(self.bc_checkout_frame)
        self.bc_gbox.setGeometry(QtCore.QRect(132, 24, 415, 525))
        self.bc_gbox.setTitle("")
        self.bc_gbox.setObjectName("bc_gbox")
        self.bc_item_info_frame = QtWidgets.QFrame(self.bc_gbox)
        self.bc_item_info_frame.setEnabled(False)
        self.bc_item_info_frame.setGeometry(QtCore.QRect(16, 172, 381, 176))
        self.bc_item_info_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bc_item_info_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bc_item_info_frame.setObjectName("bc_item_info_frame")
        self.label_7 = QtWidgets.QLabel(self.bc_item_info_frame)
        self.label_7.setGeometry(QtCore.QRect(12, 15, 141, 16))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.line = QtWidgets.QFrame(self.bc_item_info_frame)
        self.line.setGeometry(QtCore.QRect(3, 115, 363, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.bc_available_lbl = QtWidgets.QLabel(self.bc_item_info_frame)
        self.bc_available_lbl.setGeometry(QtCore.QRect(165, 55, 213, 16))
        self.bc_available_lbl.setText("")
        self.bc_available_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.bc_available_lbl.setObjectName("bc_available_lbl")
        self.bc_name_lbl = QtWidgets.QLabel(self.bc_item_info_frame)
        self.bc_name_lbl.setGeometry(QtCore.QRect(165, 8, 213, 27))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.bc_name_lbl.setFont(font)
        self.bc_name_lbl.setText("")
        self.bc_name_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.bc_name_lbl.setObjectName("bc_name_lbl")
        self.label_21 = QtWidgets.QLabel(self.bc_item_info_frame)
        self.label_21.setGeometry(QtCore.QRect(12, 75, 141, 16))
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.bc_barcode_lbl = QtWidgets.QLabel(self.bc_item_info_frame)
        self.bc_barcode_lbl.setGeometry(QtCore.QRect(165, 35, 213, 16))
        self.bc_barcode_lbl.setText("")
        self.bc_barcode_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.bc_barcode_lbl.setObjectName("bc_barcode_lbl")
        self.label_8 = QtWidgets.QLabel(self.bc_item_info_frame)
        self.label_8.setGeometry(QtCore.QRect(12, 35, 141, 16))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.bc_subtotal_lbl = QtWidgets.QLabel(self.bc_item_info_frame)
        self.bc_subtotal_lbl.setGeometry(QtCore.QRect(165, 130, 213, 16))
        self.bc_subtotal_lbl.setText("")
        self.bc_subtotal_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.bc_subtotal_lbl.setObjectName("bc_subtotal_lbl")
        self.bc_provider_lbl = QtWidgets.QLabel(self.bc_item_info_frame)
        self.bc_provider_lbl.setGeometry(QtCore.QRect(165, 95, 213, 16))
        self.bc_provider_lbl.setText("")
        self.bc_provider_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.bc_provider_lbl.setObjectName("bc_provider_lbl")
        self.label_14 = QtWidgets.QLabel(self.bc_item_info_frame)
        self.label_14.setGeometry(QtCore.QRect(-32, 55, 185, 16))
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.label_36 = QtWidgets.QLabel(self.bc_item_info_frame)
        self.label_36.setGeometry(QtCore.QRect(12, 95, 141, 16))
        self.label_36.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_36.setObjectName("label_36")
        self.bc_price_lbl = QtWidgets.QLabel(self.bc_item_info_frame)
        self.bc_price_lbl.setGeometry(QtCore.QRect(165, 75, 213, 16))
        self.bc_price_lbl.setText("")
        self.bc_price_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.bc_price_lbl.setObjectName("bc_price_lbl")
        self.label_43 = QtWidgets.QLabel(self.bc_item_info_frame)
        self.label_43.setGeometry(QtCore.QRect(24, 130, 141, 16))
        self.label_43.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_43.setObjectName("label_43")
        self.bc_remove_btn = QtWidgets.QPushButton(self.bc_gbox)
        self.bc_remove_btn.setEnabled(False)
        self.bc_remove_btn.setGeometry(QtCore.QRect(112, 404, 183, 35))
        self.bc_remove_btn.setObjectName("bc_remove_btn")
        self.bc_btn_frame = QtWidgets.QFrame(self.bc_gbox)
        self.bc_btn_frame.setEnabled(False)
        self.bc_btn_frame.setGeometry(QtCore.QRect(92, 352, 221, 156))
        self.bc_btn_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bc_btn_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bc_btn_frame.setObjectName("bc_btn_frame")
        self.bc_get_payment_btn = QtWidgets.QPushButton(self.bc_btn_frame)
        self.bc_get_payment_btn.setGeometry(QtCore.QRect(20, 108, 183, 35))
        self.bc_get_payment_btn.setObjectName("bc_get_payment_btn")
        self.bc_add_btn = QtWidgets.QPushButton(self.bc_btn_frame)
        self.bc_add_btn.setGeometry(QtCore.QRect(20, 13, 183, 35))
        self.bc_add_btn.setObjectName("bc_add_btn")
        self.bc_search_frame = QtWidgets.QFrame(self.bc_gbox)
        self.bc_search_frame.setGeometry(QtCore.QRect(46, 7, 301, 161))
        self.bc_search_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bc_search_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bc_search_frame.setObjectName("bc_search_frame")
        self.bc_barcode_search_field = QtWidgets.QLineEdit(self.bc_search_frame)
        self.bc_barcode_search_field.setGeometry(QtCore.QRect(113, 6, 161, 20))
        self.bc_barcode_search_field.setClearButtonEnabled(True)
        self.bc_barcode_search_field.setObjectName("bc_barcode_search_field")
        self.label = QtWidgets.QLabel(self.bc_search_frame)
        self.label.setGeometry(QtCore.QRect(18, 10, 89, 13))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.bc_search_btn = QtWidgets.QPushButton(self.bc_search_frame)
        self.bc_search_btn.setGeometry(QtCore.QRect(68, 40, 183, 35))
        self.bc_search_btn.setObjectName("bc_search_btn")
        self.bc_quantity_frame = QtWidgets.QFrame(self.bc_search_frame)
        self.bc_quantity_frame.setEnabled(False)
        self.bc_quantity_frame.setGeometry(QtCore.QRect(70, 76, 161, 80))
        self.bc_quantity_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bc_quantity_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bc_quantity_frame.setObjectName("bc_quantity_frame")
        self.bc_weight_lbl = QtWidgets.QLabel(self.bc_quantity_frame)
        self.bc_weight_lbl.setGeometry(QtCore.QRect(-7, 52, 89, 13))
        self.bc_weight_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bc_weight_lbl.setObjectName("bc_weight_lbl")
        self.bc_weight_sbox = QtWidgets.QDoubleSpinBox(self.bc_quantity_frame)
        self.bc_weight_sbox.setGeometry(QtCore.QRect(88, 47, 62, 22))
        self.bc_weight_sbox.setSingleStep(0.1)
        self.bc_weight_sbox.setObjectName("bc_weight_sbox")
        self.bc_quantity_sbox = QtWidgets.QSpinBox(self.bc_quantity_frame)
        self.bc_quantity_sbox.setGeometry(QtCore.QRect(88, 13, 42, 22))
        self.bc_quantity_sbox.setMinimum(1)
        self.bc_quantity_sbox.setProperty("value", 1)
        self.bc_quantity_sbox.setObjectName("bc_quantity_sbox")
        self.bc_quantity_lbl = QtWidgets.QLabel(self.bc_quantity_frame)
        self.bc_quantity_lbl.setGeometry(QtCore.QRect(-7, 17, 89, 13))
        self.bc_quantity_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bc_quantity_lbl.setObjectName("bc_quantity_lbl")
        self.bc_btn_frame.raise_()
        self.bc_item_info_frame.raise_()
        self.bc_remove_btn.raise_()
        self.bc_search_frame.raise_()
        self.bc_load_reservation_btn = QtWidgets.QPushButton(self.bc_checkout_frame)
        self.bc_load_reservation_btn.setGeometry(QtCore.QRect(914, 114, 141, 35))
        self.bc_load_reservation_btn.setObjectName("bc_load_reservation_btn")
        self.bc_customer_name_field = QtWidgets.QLineEdit(self.bc_checkout_frame)
        self.bc_customer_name_field.setGeometry(QtCore.QRect(914, 26, 141, 20))
        self.bc_customer_name_field.setPlaceholderText("")
        self.bc_customer_name_field.setClearButtonEnabled(True)
        self.bc_customer_name_field.setObjectName("bc_customer_name_field")
        self.bc_reservation_num_sbox = QtWidgets.QSpinBox(self.bc_checkout_frame)
        self.bc_reservation_num_sbox.setGeometry(QtCore.QRect(914, 74, 141, 22))
        self.bc_reservation_num_sbox.setWrapping(True)
        self.bc_reservation_num_sbox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.bc_reservation_num_sbox.setProperty("showGroupSeparator", False)
        self.bc_reservation_num_sbox.setSuffix("")
        self.bc_reservation_num_sbox.setMinimum(0)
        self.bc_reservation_num_sbox.setMaximum(999999)
        self.bc_reservation_num_sbox.setProperty("value", 0)
        self.bc_reservation_num_sbox.setObjectName("bc_reservation_num_sbox")
        self.label_2 = QtWidgets.QLabel(self.bc_checkout_frame)
        self.label_2.setGeometry(QtCore.QRect(914, 56, 141, 16))
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_28 = QtWidgets.QLabel(self.bc_checkout_frame)
        self.label_28.setGeometry(QtCore.QRect(914, 8, 141, 16))
        self.label_28.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.bc_checkout_frame.raise_()
        self.bc_begin_checkout_btn.raise_()
        self.tabWidget.addTab(self.begin_checkout_tab, "")
        self.employee_id_lbl = QtWidgets.QLabel(self.centralwidget)
        self.employee_id_lbl.setGeometry(QtCore.QRect(4, 6, 53, 33))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.employee_id_lbl.setFont(font)
        self.employee_id_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.employee_id_lbl.setObjectName("employee_id_lbl")
        self.employee_name_lbl = QtWidgets.QLabel(self.centralwidget)
        self.employee_name_lbl.setGeometry(QtCore.QRect(70, 6, 321, 33))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.employee_name_lbl.setFont(font)
        self.employee_name_lbl.setObjectName("employee_name_lbl")
        self.log_out_btn = QtWidgets.QPushButton(self.centralwidget)
        self.log_out_btn.setGeometry(QtCore.QRect(919, 10, 183, 35))
        self.log_out_btn.setObjectName("log_out_btn")
        self.error_lbl = QtWidgets.QLabel(self.centralwidget)
        self.error_lbl.setGeometry(QtCore.QRect(336, 10, 569, 21))
        self.error_lbl.setText("")
        self.error_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.error_lbl.setObjectName("error_lbl")
        main_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)

        self.retranslateUi(main_window)
        self.tabWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(main_window)
        main_window.setTabOrder(self.me_name_field, self.me_password_field)
        main_window.setTabOrder(self.me_password_field, self.me_role_cbox)
        main_window.setTabOrder(self.me_role_cbox, self.me_update_employee_btn)
        main_window.setTabOrder(self.me_update_employee_btn, self.me_create_new_employee_btn)
        main_window.setTabOrder(self.me_create_new_employee_btn, self.me_delete_employee_btn)
        main_window.setTabOrder(self.me_delete_employee_btn, self.me_employee_listview)
        main_window.setTabOrder(self.me_employee_listview, self.mp_barcode_search_field)
        main_window.setTabOrder(self.mp_barcode_search_field, self.mp_search_btn)
        main_window.setTabOrder(self.mp_search_btn, self.mp_name_field)
        main_window.setTabOrder(self.mp_name_field, self.mp_quantity_rb)
        main_window.setTabOrder(self.mp_quantity_rb, self.mp_weight_rb)
        main_window.setTabOrder(self.mp_weight_rb, self.mp_update_btn)
        main_window.setTabOrder(self.mp_update_btn, self.mp_add_btn)
        main_window.setTabOrder(self.mp_add_btn, self.mp_delete_btn)
        main_window.setTabOrder(self.mp_delete_btn, self.bc_barcode_search_field)
        main_window.setTabOrder(self.bc_barcode_search_field, self.bc_search_btn)
        main_window.setTabOrder(self.bc_search_btn, self.bc_quantity_sbox)
        main_window.setTabOrder(self.bc_quantity_sbox, self.bc_weight_sbox)
        main_window.setTabOrder(self.bc_weight_sbox, self.bc_add_btn)
        main_window.setTabOrder(self.bc_add_btn, self.bc_remove_btn)
        main_window.setTabOrder(self.bc_remove_btn, self.bc_get_payment_btn)
        main_window.setTabOrder(self.bc_get_payment_btn, self.bc_receipt_listview)
        main_window.setTabOrder(self.bc_receipt_listview, self.bc_cancel_btn)
        main_window.setTabOrder(self.bc_cancel_btn, self.log_out_btn)
        main_window.setTabOrder(self.log_out_btn, self.bc_begin_checkout_btn)
        main_window.setTabOrder(self.bc_begin_checkout_btn, self.tabWidget)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "MainWindow"))
        self.me_employee_gbox.setTitle(_translate("main_window", "Employee"))
        self.me_delete_employee_btn.setText(_translate("main_window", "Delete Employee"))
        self.label_4.setText(_translate("main_window", "Employee ID"))
        self.me_update_employee_btn.setText(_translate("main_window", "Update Employee"))
        self.label_5.setText(_translate("main_window", "Employee Name"))
        self.label_6.setText(_translate("main_window", "Password"))
        self.me_role_cbox.setItemText(0, _translate("main_window", "Admin"))
        self.me_role_cbox.setItemText(1, _translate("main_window", "Cashier"))
        self.me_create_new_employee_btn.setText(_translate("main_window", "Create a New Employee"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.manage_employees_tab), _translate("main_window", "Manage Employees"))
        self.label_33.setText(_translate("main_window", "Barcode Search"))
        self.mp_search_btn.setText(_translate("main_window", "Search"))
        self.mp_product_gbox.setTitle(_translate("main_window", "Product Information"))
        self.mp_delete_btn.setText(_translate("main_window", "Delete Product"))
        self.mp_update_btn.setText(_translate("main_window", "Update Product"))
        self.label_9.setText(_translate("main_window", "Available Units"))
        self.label_15.setText(_translate("main_window", "Customer Price"))
        self.label_13.setText(_translate("main_window", "Provider"))
        self.label_12.setText(_translate("main_window", "Price"))
        self.label_11.setText(_translate("main_window", "Procuct Name"))
        self.label_10.setText(_translate("main_window", "Barcode"))
        self.mp_weight_rb.setText(_translate("main_window", "Weight"))
        self.mp_quantity_rb.setText(_translate("main_window", "Quantity"))
        self.label_19.setText(_translate("main_window", "Priced By"))
        self.mp_customer_price_sbox.setPrefix(_translate("main_window", "$ "))
        self.mp_price_sbox.setPrefix(_translate("main_window", "$ "))
        self.mp_available_units_2_sbox.setPrefix(_translate("main_window", " "))
        self.mp_available_units_2_sbox.setSuffix(_translate("main_window", " lbs"))
        self.mp_add_btn.setText(_translate("main_window", "Add a New Product"))
        self.mp_import_btn.setText(_translate("main_window", "Import from Excel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.manage_products_tab), _translate("main_window", "Manage Products"))
        self.groupBox_5.setTitle(_translate("main_window", "Point Conversion Management"))
        self.label_24.setText(_translate("main_window", "Customers earn:"))
        self.label_26.setText(_translate("main_window", "for every $1 spent"))
        self.label_27.setText(_translate("main_window", "are equivalent to $1.00"))
        self.label_31.setText(_translate("main_window", "When buying products with points:"))
        self.earn_sbox.setSuffix(_translate("main_window", " pt(s)"))
        self.spend_sbox.setSuffix(_translate("main_window", " pt(s)"))
        self.mc_update_rules_btn.setText(_translate("main_window", "Update Point Rules"))
        self.label_38.setText(_translate("main_window", "Customer Name/ID Search"))
        self.mc_search_btn.setText(_translate("main_window", "Search"))
        self.mc_customer_gbox.setTitle(_translate("main_window", "Customer Information"))
        self.mc_update_btn.setText(_translate("main_window", "Update Customer Info"))
        self.label_39.setText(_translate("main_window", "Point Balance"))
        self.label_44.setText(_translate("main_window", "Customer Name"))
        self.label_45.setText(_translate("main_window", "Customer ID"))
        self.mc_point_balance_sbox.setSuffix(_translate("main_window", " pt(s)"))
        self.mc_activity_cb.setText(_translate("main_window", "Active Customer"))
        self.mc_add_btn.setText(_translate("main_window", "Add a New Customer"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.manage_customers_tab), _translate("main_window", "Manage Customers"))
        self.mo_date_lbl.setText(_translate("main_window", "Date Label"))
        self.groupBox.setTitle(_translate("main_window", "Search By Receipt ID"))
        self.label_34.setText(_translate("main_window", "Receipt ID"))
        self.mo_search_btn.setText(_translate("main_window", "Search"))
        self.groupBox_2.setTitle(_translate("main_window", "Search by Date"))
        self.mo_date_edit.setDisplayFormat(_translate("main_window", "MM/dd/yyyy"))
        self.mo_total_lbl.setText(_translate("main_window", "$0.00"))
        self.mo_r_subtotal_lbl.setText(_translate("main_window", "$0.00"))
        self.label_20.setText(_translate("main_window", "Subtotal"))
        self.label_22.setText(_translate("main_window", "Total"))
        self.mo_tax_lbl.setText(_translate("main_window", "$0.00"))
        self.label_23.setText(_translate("main_window", "Tax"))
        self.mo_return_btn.setText(_translate("main_window", "Return Item"))
        self.mo_date_lbl_3.setText(_translate("main_window", "or"))
        self.mo_r_date_lbl_33.setText(_translate("main_window", "Date:"))
        self.mo_r_date_lbl_2.setText(_translate("main_window", "Cashier:"))
        self.mo_r_date_lbl_3.setText(_translate("main_window", "Payment Method:"))
        self.mo_r_date_lbl_4.setText(_translate("main_window", "Receipt ID:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.manage_orders_tab), _translate("main_window", "Manage Orders"))
        self.r_date_edit_start.setDisplayFormat(_translate("main_window", "MM/dd/yyyy"))
        self.r_date_edit_end.setDisplayFormat(_translate("main_window", "MM/dd/yyyy"))
        self.r_beg_lbl.setText(_translate("main_window", "Beginning Date"))
        self.r_end_lbl.setText(_translate("main_window", "Ending Date"))
        self.r_print_btn.setText(_translate("main_window", "Print Report"))
        self.label_3.setText(_translate("main_window", "Total Orders:"))
        self.label_25.setText(_translate("main_window", "Total Revenue:"))
        self.groupBox_3.setTitle(_translate("main_window", "Printed Report Sorting"))
        self.r_revenue_rb.setText(_translate("main_window", "By Revenue"))
        self.r_total_rb.setText(_translate("main_window", "By Total Sold"))
        self.r_unordered_rb.setText(_translate("main_window", "Unordered"))
        self.r_alpha_rb.setText(_translate("main_window", "Alphabetically"))
        self.groupBox_4.setTitle(_translate("main_window", "Printed Report Order"))
        self.r_asc_rb.setText(_translate("main_window", "Ascending"))
        self.r_desc_rb.setText(_translate("main_window", "Descending"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.reports_tab), _translate("main_window", "Reports"))
        self.bc_begin_checkout_btn.setText(_translate("main_window", "Begin Checkout"))
        self.bc_total_lbl.setText(_translate("main_window", "$0.00"))
        self.bc_r_subtotal_lbl.setText(_translate("main_window", "$0.00"))
        self.label_18.setText(_translate("main_window", "Subtotal"))
        self.label_17.setText(_translate("main_window", "Total"))
        self.bc_tax_lbl.setText(_translate("main_window", "$0.00"))
        self.label_16.setText(_translate("main_window", "Tax"))
        self.bc_cancel_btn.setText(_translate("main_window", "Cancel Transaction"))
        self.label_7.setText(_translate("main_window", "Item Name"))
        self.label_21.setText(_translate("main_window", "Price per Unit"))
        self.label_8.setText(_translate("main_window", "Barcode Number"))
        self.label_14.setText(_translate("main_window", "Number of Available Units"))
        self.label_36.setText(_translate("main_window", "Provider"))
        self.label_43.setText(_translate("main_window", "Item subtotal  $"))
        self.bc_remove_btn.setText(_translate("main_window", "Remove Item(s)"))
        self.bc_get_payment_btn.setText(_translate("main_window", "Get Payment"))
        self.bc_add_btn.setText(_translate("main_window", "Add Item"))
        self.label.setText(_translate("main_window", "Item Barcode"))
        self.bc_search_btn.setText(_translate("main_window", "Search"))
        self.bc_weight_lbl.setText(_translate("main_window", "Weight"))
        self.bc_quantity_lbl.setText(_translate("main_window", "Quantity"))
        self.bc_load_reservation_btn.setText(_translate("main_window", "Load Reservation(s)"))
        self.label_2.setText(_translate("main_window", "Reservation Number"))
        self.label_28.setText(_translate("main_window", "Customer Name or ID"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.begin_checkout_tab), _translate("main_window", "Begin Checkout"))
        self.employee_id_lbl.setText(_translate("main_window", "Employee ID"))
        self.employee_name_lbl.setText(_translate("main_window", "Employee Name"))
        self.log_out_btn.setText(_translate("main_window", "Log Out"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_window = QtWidgets.QMainWindow()
    ui = Ui_main_window()
    ui.setupUi(main_window)
    main_window.show()
    sys.exit(app.exec_())

